//! The asteroid field: generated by [`spaceships_sim`], shipped in the shape
//! [`spaceships_protocol`] demands.
//!
//! # Seed in, records out
//!
//! `sim` generates the field from a single `u64` so that a client can rebuild
//! it locally from eight bytes instead of receiving sixty records — that is the
//! entire reason [`spaceships_sim::asteroids`] exists and why it is so careful
//! about draw order and transcendental functions.
//!
//! **This server still sends the records.** Not because the seed is a bad idea,
//! but because [`spaceships_protocol::ServerMessage::Start`] has no field to
//! put a seed in: its `asteroids` member is a `Vec<Asteroid>`, pinned by the
//! protocol crate's round-trip tests and consumed by the unmodified browser
//! client, which has no seeded generator to rebuild from. Adding a `seed` field
//! is a protocol change, and `protocol` is off limits here. See the crate docs
//! for the report.
//!
//! What is gained anyway, today, is everything *behind* the seed:
//!
//! - **The moon bug is fixed.** `generateAsteroidField` in `server/index.js`
//!   checks candidate placements against `MOTHERSHIP_AVOID` only. The
//!   motherships sit at `z = ±600` with a half-depth of 35 and the field's
//!   outer radius is 400, so `clipsMothership` **cannot reject a placement** —
//!   it has never rejected one in production. Meanwhile the moon is a sphere of
//!   radius 80 at the origin and the field starts at `30 + size` units out, so
//!   every space match generates rocks *inside the moon*, where they are
//!   invisible, effectively immortal (bullets are consumed before the moon
//!   obstacle test runs), and lethal to touch.
//!   [`spaceships_sim::asteroids::avoid_volumes`] includes the moon, so they no
//!   longer are.
//! - **The fallback placement is fixed.** After ten failed attempts the JS
//!   falls back to `[(rand-0.5)*radius, 0, (rand-0.5)*radius]` with no
//!   avoidance check at all — `y = 0` is the moon's equatorial plane and the
//!   distribution's mode is the moon's dead centre.
//! - **The field is reproducible.** The seed is stored on the room, so a match
//!   can be replayed exactly.
//!
//! This is a **gameplay change**, and an intentional one: rocks that used to
//! spawn inside the moon now spawn outside it. It is flagged in the report.

use spaceships_protocol::{Asteroid, AsteroidTier, MapKind};
use spaceships_sim::asteroids;
use spaceships_sim::math::Vec3 as SimVec3;
use spaceships_sim::rng::Rng;
use spaceships_sim::rules::Rules;
use spaceships_sim::world::{
    AsteroidTier as SimTier, MapKind as SimMapKind, Mode, RNG_STREAM_FIELD,
};

/// Generates a match's asteroid field from `seed`.
///
/// The terrain map has none — `main.js` builds its field from an empty array,
/// and `server/index.js` short-circuits with `room.map === 'terrain' ? [] :
/// …`. The `Vec` is empty, never absent: the protocol types `asteroids` as a
/// list and the client iterates it unconditionally.
///
/// The RNG is drawn from [`RNG_STREAM_FIELD`], the same stream
/// [`spaceships_sim::asteroids::populate`] uses, so a client that builds a
/// [`spaceships_sim::world::World`] from this seed reproduces this exact field
/// — which is what makes a future switch to shipping the seed a pure
/// subtraction.
#[must_use]
pub fn generate(seed: u64, map: MapKind) -> Vec<Asteroid> {
    let sim_map = match map {
        MapKind::Space => SimMapKind::Space,
        MapKind::Terrain => SimMapKind::Terrain,
    };
    let mut rng = Rng::with_stream(seed, RNG_STREAM_FIELD);
    asteroids::generate(&mut rng, &Rules::DEFAULT, Mode::Multiplayer, sim_map)
        .into_iter()
        .map(|a| Asteroid {
            id: a.id,
            pos: vec3(a.pos),
            rot: vec3(a.rot),
            size: a.size,
            hp: a.hp,
            tier: tier(a.tier),
            variant: a.variant,
            spin: vec3(a.spin),
        })
        .collect()
}

/// `sim`'s `Vec3` struct to the protocol's bare `[x, y, z]` array.
fn vec3(v: SimVec3) -> [f64; 3] {
    [v.x, v.y, v.z]
}

fn tier(t: SimTier) -> AsteroidTier {
    match t {
        SimTier::Small => AsteroidTier::Small,
        SimTier::Medium => AsteroidTier::Medium,
        SimTier::Big => AsteroidTier::Big,
        SimTier::Huge => AsteroidTier::Huge,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_space_field_has_sixty_rocks_like_the_js() {
        let field = generate(0xA57E_2011_D000_0001, MapKind::Space);
        assert_eq!(field.len(), 60);
        // Ids are 0-based and dense, which is the convention `server/index.js`
        // uses (`id: i`) and the one `asteroid-hit` indexes by.
        for (i, a) in field.iter().enumerate() {
            assert_eq!(a.id, i as u32);
        }
    }

    #[test]
    fn the_terrain_map_has_no_field() {
        assert!(generate(1, MapKind::Terrain).is_empty());
    }

    #[test]
    fn the_same_seed_regenerates_the_same_field() {
        let a = generate(12345, MapKind::Space);
        let b = generate(12345, MapKind::Space);
        assert_eq!(a, b);
        assert_ne!(generate(12346, MapKind::Space), a);
    }

    #[test]
    fn no_rock_is_generated_inside_the_moon() {
        // The live JS bug. The moon is a sphere of radius 80 at the origin;
        // `server/index.js` never tests against it, so roughly the inner shell
        // of every field ends up buried in it.
        let rules = Rules::DEFAULT;
        let moon_r = rules.world.moon_radius;
        for seed in 0..25u64 {
            for a in generate(seed, MapKind::Space) {
                let d = (a.pos[0] * a.pos[0] + a.pos[1] * a.pos[1] + a.pos[2] * a.pos[2]).sqrt();
                assert!(
                    d > moon_r,
                    "seed {seed}: rock {} at distance {d} is inside the moon (r {moon_r})",
                    a.id
                );
            }
        }
    }

    #[test]
    fn hit_points_match_the_tier_table() {
        for a in generate(99, MapKind::Space) {
            let expected = match a.tier {
                AsteroidTier::Small => 5,
                AsteroidTier::Medium => 10,
                AsteroidTier::Big => 30,
                AsteroidTier::Huge => 50,
            };
            assert_eq!(a.hp, expected, "rock {} tier {:?}", a.id, a.tier);
            assert!(a.variant < 6, "variant out of the JS range: {}", a.variant);
        }
    }

    #[test]
    fn the_wire_shape_matches_the_js_object() {
        let a = &generate(7, MapKind::Space)[0];
        // Serialize to a *string*, not to a `Value`: `serde_json::Value`'s map
        // is a `BTreeMap`, so `to_value` sorts the keys alphabetically and
        // would hide the very thing under test. The real output path is
        // `to_string`, which streams fields in declaration order — the same
        // order `server/index.js:573` pushes them.
        let json = serde_json::to_string(a).unwrap();
        let keys: Vec<&str> = json
            .match_indices('"')
            .map(|(i, _)| i)
            .collect::<Vec<_>>()
            .chunks(2)
            .filter_map(|w| match w {
                [a, b] => Some(&json[a + 1..*b]),
                _ => None,
            })
            .filter(|k| {
                matches!(
                    *k,
                    "id" | "pos" | "rot" | "size" | "hp" | "tier" | "variant" | "spin"
                )
            })
            .collect();
        assert_eq!(
            keys,
            ["id", "pos", "rot", "size", "hp", "tier", "variant", "spin"],
            "key order drifted in {json}"
        );

        let value = serde_json::to_value(a).unwrap();
        assert!(value["tier"].is_string());
        assert_eq!(value["pos"].as_array().unwrap().len(), 3);
        assert_eq!(value["spin"].as_array().unwrap().len(), 3);
    }
}
